name: '[CD] Deploy Website'

on:
  workflow_dispatch:

  pull_request: 
    types:
    - closed
    branches:
    - main
    paths:
    - 'src/dataformorocco/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: 'Deploy Website'
    runs-on: ubuntu-latest
    env:
      HUGO_PROJECT_PATH: ${{ github.workspace }}/src/dataformorocco
      HUGO_BUILD_PATH: ${{ github.workspace }}/src/dataformorocco/public
      HUGO_ENVIRONMENT: production
      HUGO_ENV: production
    steps:
    - name: 'Checkout branch'
      uses: 'actions/checkout@v3'
      with:
        submodules: true
        fetch-depth: 0
  
    - name: 'Setup Hugo'
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.113.0'
        extended: true

    - name: 'Build Website'
      run: hugo --minify
      working-directory: ${{ env.HUGO_PROJECT_PATH }}
      
    - name: 'Upload GitHub Pages artifact'
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: ${{ env.HUGO_BUILD_PATH }}
        
    - name: 'Deploy GitHub Pages site'
      uses: actions/deploy-pages@v2.0.1